# Generated by Django 4.2.6 on 2023-12-11 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capital',
            name='country_code',
            field=models.IntegerField(default=True),
        ),
        migrations.AlterField(
            model_name='emp',
            name='Dept_no',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.dept'),
        ),
    ]
